### PR TITLE
Routes - This PR addresses PR #31 

### PR DESCRIPTION
**Pull request by monicamow**
This PR addresses PR #31

Branch changes

- I moved all commits from home_route to Routes

Code changes

- home page route action now redirects to /topics
- code in home route action moved to /topics action

### CODE REVIEW

**Comment by cody-code-wy** [comment]
This should be a merge into `Routes` from a personal branch. Also the /routes should not have erb files.

**Comment by monicamow** [comment]
@cody-code-wy then what should it have

if you want me to take something out, please tell me what to replace it with

**Comment by cody-code-wy** [comment]
@monicamow the ERBs should go into a branch for ERBs, not a branch for routes.

Additionally Routes is a feature branch, not a development branch. The correct usage would be to create a branch off of `Routes` and do a PR to `Routes`

**Comment by monicamow** [comment]
@wyoung ok that makes more sense. I thought you meant our /routes will never use ERBs. but what you meant was...do separate branches for actions and for erbs

**Pull request closed without merging**
