### PR TITLE
Server side

### PR DESCRIPTION
**Pull request by cody-code-wy**
Merge all routes to development.

### CODE REVIEW

**Comment by tjukes** [comment]
Good idea to add all the updated code from most recent PRs to the server_side branch and test the integration there before pushing to the development branch!

**Comment by monicamow** [comment]
yes, now I see where the merges from #36 and #41 went

**Comment by cody-code-wy** [comment]
@monicamow  Look at her the top where it has 'wants to merge 8 commits into development from server_side`

**Comment by cody-code-wy** [comment]
Closed, there are missing PRs for server_side.

**Pull request closed without merging**
